### ISSUE TITLE
"Clear Log" button fails, no clear type is passed

### ISSUE THREAD

**Issue by oaknuggins** [Merkoba/Hue#1]
Clear Log button from the main menu fails to work, as the clear type isn't passed.

"Invalid type. Available types are: all, above, below"

**Comment by madprops** [comment]
Thanks. Fixed in https://github.com/Merkoba/Hue/commit/ac2267722255c635bc7d9a45027e64ece24550c5

Basically I just added a default value to type:

```Hue.clear_log = function(type="all", id=false)```
