### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by r4de** [Merkoba/Hue#2]
Hi Mad,

by trying to log in, I got "Wrong email or password".
After a few attempts "Too many requests, please try again later."

edit: Registered again with the same email and nick and it works again.
Did someone deleted my account?!

**Comment by madprops** [comment]
Hi. No your account wasn't deleted. Some days ago some database upgrade went wrong, which forced me to revert the host to an earlier snapshot, which resulted in all activity from roughly a week to be reverted, including your account. Sorry for the inconvenience.

**Comment by r4de** [comment]
Ah O.K....thx

btw. nice project and features.
